### ISSUE TITLE
Tracking User Behavior 

### ISSUE THREAD

**Issue by dwilliams326** [kdoffor1k/The-Archaic-Tower#30]
## Story/Task Details
- [ ] Collect data on the players use of spells
- [ ] Create a histogram using data collected from player input
- [ ] Create menu to display statistics of the players game
- [ ] Stats include things such as: accuracy, most used spell components, least used spell components, amount of time played, etc.

## Acceptance Scenarios
- Given: A player is in the main menu
- When: clicks on the statistics menu
- Then: different statistics about the players gameplay will be displayed to the player

## Done Done Criteria
There is a new statistics menu
Data collected from the player during gameplay will be displayed in the statistics menu
A histogram will be created, displaying the number of times a player has used a certain spell component
